#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend nejoseph.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 445805-web-01 107.22.143.158:80
        server 445805-web-02 52.3.246.170.6:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
